image: fedora:latest

variables:
  CI_NAME: "GitLab CI"

stages:
  - download
  - compile
  - test

before_script:
  - dnf -qy update && dnf -y install zip
  - curl -s "https://get.sdkman.io" | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java
  - sdk install kotlin
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

download:
  stage: download
  script:
    - ./bld download

compile:
  stage: compile
  script:
    - ./bld compile

test:
  stage: test
  allow_failure: true
  script:
    - ./bld test

reporter:
  stage: test
  when: on_failure
  script:
    - ./bld reporter --all
