image: ubuntu:latest

variables:
  CI_NAME: "GitLab CI"

stages:
  - test

before_script:
  - apt-get update -qq && apt-get install -y curl zip
  - curl -s "https://get.sdkman.io" | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk install java 17.0.11-tem
  - sdk install kotlin 2.0.0
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

test:
  stage: test
  script:
    - ./bld download
    - ./bld compile
    - ./bld test
