language: java

jdk:
  - oraclejdk8
  - openjdk12

before_install:
  - chmod +x gradlew

after_success:
  - |
      if [ "${TRAVIS_PULL_REQUEST}" != "false" ] && [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
          ./gradlew sonarqube -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization=${SONAR_GITHUB}
      fi
