language: java

jdk:
  - oraclejdk8
  - openjdk12

before_install:
  - chmod +x gradlew

after_success:
  - |
      if [ "${TRAVIS_PULL_REQUEST}" != "false" ] && [ "$TRAVIS_JDK_VERSION" == oraclejdk8 ]; then
        ./gradlew sonarqube \
          -Dsonar.github.pullRequest=${TRAVIS_PULL_REQUEST} \
          -Dsonar.github.oauth=${SONAR_GITHUB} \
          -Dsonar.login=${SONAR_TOKEN}
      fi
