language: java
dist: trusty

env:
  global:
    - CI_NAME: "Travis CI"

install:
  - git fetch --unshallow --tags

addons:
  sonarcloud:
    organization: "ethauvin-github"

jdk:
  - openjdk11
  - openjdk14

before_install:
  - chmod +x gradlew

after_success:
  - |
      if [ "${TRAVIS_TEST_RESULT}" == 0 ] && [ "$TRAVIS_JDK_VERSION" == openjdk11 ]; then
        ./gradlew sonarqube
      fi
