language: java
dist: trusty

env:
  global:
    - CI=true

matrix:
  include:
    - jdk: openjdk9
    - env: JDK='OpenJDK 14'
      install: . ./install-jdk.sh -F 14 -C

install:
  - git fetch --unshallow --tags

addons:
  sonarcloud:
    organization: "ethauvin-github"

before_install:
  - chmod +x gradlew

after_success:
  - |
      if [ "${TRAVIS_TEST_RESULT}" == 0 ] && [ "$TRAVIS_JDK_VERSION" == oraclejdk9 ]; then
        ./gradlew sonarqube
      fi
