image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Test with bld
        script:
          # Install latest Java & Kotlin via SDKMAN!
          - apt-get update -qq && apt-get install -y curl zip
          - curl -s "https://get.sdkman.io" | bash
          - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
          - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
          - source "$HOME/.sdkman/bin/sdkman-init.sh"
          - sdk install java
          - sdk install kotlin
          - source "$HOME/.sdkman/bin/sdkman-init.sh"
          # Download, compile and test with bld
          - ./bld download
          - ./bld compile
          - ./bld test
