version: 2.1

orbs:
  sdkman: joshdholtz/sdkman@0.2.0

executors:
  jdk:
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/openjdk:<< parameters.tag >>
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      CI_NAME: CircleCI

commands:
  build_and_test:
    steps:
      - checkout
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: kotlin
          version: 2.4.0
      - restore_cache:
          key: bld-lib-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Compile source
          command: ./bld clean compile
      - save_cache:
          key: bld-lib-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - lib
      - run:
          name: Run tests
          command: ./bld jacoco
      - run:
          name: Run reporter
          when: on_fail
          command: ./bld --offline reporter --all
      - store_test_results:
          path: build/test-results/test/
      - store_artifacts:
          path: build/reports/jacoco/test/html

jobs:
  test:
    parameters:
      jdk_version:
        type: string
    executor:
      name: jdk
      tag: << parameters.jdk_version >>
    steps:
      - build_and_test

workflows:
  bld:
    jobs:
      - test:
          name: jdk25
          jdk_version: "25.0"
      - test:
          name: jdk21
          jdk_version: "21.0"
