/*
 * This file is automatically generated
 * Do not modify! -- ALL CHANGES WILL BE ERASED!
 */

package net.thauvin.erik.mobibot

import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId

/**
 * Provides release information.
 */
object ReleaseInfo {
    const val PROJECT = "mobibot"
    const val VERSION = "0.8.0-rc+20240712110931"

    @JvmField
    @Suppress("MagicNumber")
    val BUILD_DATE: LocalDateTime = LocalDateTime.ofInstant(
        Instant.ofEpochMilli(1720807771484L), ZoneId.systemDefault()
    )

    const val WEBSITE = "https://mobitopia.org/mobibot/"
    const val AUTHOR = "Erik C. Thauvin"
    const val AUTHOR_URL = "https://erik.thauvin.net/"
}
